// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pat2023_lukasz_winowicz_dotnet.Entities.Database;

#nullable disable

namespace pat2023lukaszwinowiczdotnet.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230108094647_added_authors_and_books")]
    partial class addedauthorsandbooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pat2023_lukasz_winowicz_dotnet.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1949, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Haruki",
                            Gender = false,
                            LastName = "Murakami"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1892, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "J.R.R.",
                            Gender = false,
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "J.K.",
                            Gender = true,
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1889, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ernest",
                            Gender = false,
                            LastName = "Hemingway"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1775, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = true,
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1947, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stephen",
                            Gender = false,
                            LastName = "King"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1943, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elena",
                            Gender = true,
                            LastName = "Ferrante"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1942, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = false,
                            LastName = "Irving"
                        });
                });

            modelBuilder.Entity("pat2023_lukasz_winowicz_dotnet.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("PublicationDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the first novel in which Murakami takes up the risky topic of fringe religious groups—a sore spot in Japan since the Aum Shinrikyō terrorist attack of 1995.",
                            ISBN = "XXX123",
                            PublicationDate = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 7.5m,
                            Title = "1Q84 Tom 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "In 1Q84 ...",
                            ISBN = "XXX124",
                            PublicationDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 7.5m,
                            Title = "1Q84 Tom 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bilbo Baggins, the protagonist, is a respectable, reserved hobbit—a race resembling short humans with furry, leathery feet who live in underground houses and are mainly pastoral farmers and gardeners.",
                            ISBN = "XXX125",
                            PublicationDate = new DateTime(1937, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 6.8m,
                            Title = "Hobbit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Surely the most confusing of all Murakami novels, this one has three protagonists, each from a different generation.",
                            ISBN = "XXX126",
                            PublicationDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 7.5m,
                            Title = "Kafka on the Shore"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Lord of the Rings is an epic[1] high-fantasy novel[a] by English author and scholar J. R. R. Tolkien. Set in Middle-earth, intended to be Earth at some time in the distant past, the story began as a sequel to Tolkien's 1937 children's book The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling books ever written, with over 150 million copies sold.",
                            ISBN = "XXX127",
                            PublicationDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 9.2m,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Harry Potter lives with his abusive aunt and uncle, Vernon and Petunia Dursley and their bullying son, Dudley. On Harry's eleventh birthday, a half-giant named Rubeus Hagrid personally delivers an acceptance letter to Hogwarts School of Witchcraft and Wizardry, revealing that Harry's parents, James and Lily Potter, were wizards. When Harry was one year old, an evil and powerful dark wizard, Lord Voldemort, murdered his parents. Harry survived Voldemort's killing curse that rebounded off his forehead and seemingly destroyed the Dark Lord, leaving a lightning bolt-shaped scar on his forehead. Unknown to Harry, he is famous in the wizarding world",
                            ISBN = "XXX128",
                            PublicationDate = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.8m,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 7,
                            Description = "While spending the summer at the Dursleys, twelve-year-old Harry Potter is visited by a house-elf named Dobby. He warns that Harry is in danger and must not return to Hogwarts. Harry refuses, so Dobby magically ruins Aunt Petunia and Uncle Vernon's dinner party.",
                            ISBN = "XXX129",
                            PublicationDate = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.6m,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 8,
                            Description = "On the surface, the novel is a love story between the protagonist Jake Barnes—a man whose war wound has made him unable to have sex—and the promiscuous divorcée Lady Brett Ashley.",
                            ISBN = "XXX130",
                            PublicationDate = new DateTime(1926, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 7.3m,
                            Title = "The Sun Also Rises"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Robert Jordan is an American, formerly a professor of Spanish language at the University of Montana. He had lived in prewar Spain, and fights as an irregular soldier for the Republic against Francisco Franco's fascist forces. ",
                            ISBN = "XXX131",
                            PublicationDate = new DateTime(1940, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.4m,
                            Title = "For Whom the Bell Tolls"
                        },
                        new
                        {
                            Id = 10,
                            Description = "In the early 19th century, the Bennet family live at their Longbourn estate, situated near the village of Meryton in Hertfordshire, England. Mrs. Bennet's greatest desire is to marry off her five daughters in order to secure their futures. The arrival of Mr. Bingley, a rich bachelor who rents the neighbouring Netherfield estate, gives her hope that one of her daughters might contract an advantageous marriage, because \"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife\".",
                            ISBN = "XXX132",
                            PublicationDate = new DateTime(1813, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.9m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The Shining mainly takes place in the fictional Overlook Hotel, an isolated, haunted resort hotel located in the Colorado Rockies.",
                            ISBN = "XXX133",
                            PublicationDate = new DateTime(1977, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.3m,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The Green Mile is a 1996 serial novel by American writer Stephen King. It tells the story of death row supervisor Paul Edgecombe's encounter with John Coffey, an unusual inmate who displays inexplicable healing and empathetic abilities. ",
                            ISBN = "XXX134",
                            PublicationDate = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 9.1m,
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 13,
                            Description = "My Brilliant Friend is a rich, intense and generous hearted story about two friends, Elena and Lila. Ferrante's inimitable style lends itself perfectly to a meticulous portrait of these two women that is also the story of a nation and a touching meditation on the nature of friendship. ",
                            ISBN = "XXX135",
                            PublicationDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.7m,
                            Title = "My Brilliant Friend"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Homer Wells is shown growing up in an orphanage where he spends his childhood trying to be \"of use\" as a medical assistant to director Dr. Wilbur Larch, whose history is told in flashbacks: After a traumatic misadventure with a prostitute as a young man, Wilbur turns his back on sex and love, choosing instead to help women with unwanted pregnancies give birth and then keeping the babies in an orphanage.",
                            ISBN = "XXX136",
                            PublicationDate = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 8.6m,
                            Title = "The Cider House Rules"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The novel is about the life of T.S. Garp. His mother, Jenny Fields, is a strong-willed nurse who wants a child but not a husband.",
                            ISBN = "XXX137",
                            PublicationDate = new DateTime(1978, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 9.4m,
                            Title = "The World According to Garp"
                        });
                });

            modelBuilder.Entity("pat2023_lukasz_winowicz_dotnet.Entities.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 7
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 8
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 8
                        });
                });

            modelBuilder.Entity("pat2023_lukasz_winowicz_dotnet.Entities.BookAuthor", b =>
                {
                    b.HasOne("pat2023_lukasz_winowicz_dotnet.Entities.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pat2023_lukasz_winowicz_dotnet.Entities.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("pat2023_lukasz_winowicz_dotnet.Entities.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("pat2023_lukasz_winowicz_dotnet.Entities.Book", b =>
                {
                    b.Navigation("BookAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
